# .github/workflows/demo.yml

name: CI
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Compile Application
        run: echo "Building the application assets..."

  test:
    needs: build # Waits for build to complete
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run automated tests
        run: echo "Running test suites..."

  deploy:
    needs: [build, test] # Waits for both jobs
    runs-on: ubuntu-latest
    steps:
      - name: Deploy application
        run: echo "Deploying build artifacts to production server..."
